import Head from "next/head";
import Image from "next/image";
import Button from "@/components/Button";
import {AiFillCaretRight} from "react-icons/ai";

export default function Home() {
  return (
    <>
      <Head>
        <title>Defi Saving</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="flex items-center justify-between p-2 m-2 bg-inherit transpac ">
          <p className="font-bold text-xl">🦄 DeCrypt </p>
          <Button text="Connect Wallet" variant="primary" />
        </div>
      </header>
      <main>
        <div className="text-center my-20 ">
          <h1 className="text-6xl font-bold my-2 text-white capitalize">
            Invest in a new,in a{" "}
            <span className="text-primary-1"> new World</span>
          </h1>

          <p className="py-3">
            {" "}
            Invest beyond borders, <br /> We connect across cryptocurrency
            platforms around the world.{" "}
          </p>
          <div className="flex items-center justify-center gap-2">
            <Button text="Get Started &rarr;" variant="primary" />
            <Button text="See how it works &rarr; " />
          </div>
        </div>
        <div className=""></div>
      </main>
    </>
  );
}
